# Generated by Django 2.1.7 on 2019-05-16 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galerias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='galeriaimagenes',
            name='slug',
            field=models.SlugField(default=1, editable=False, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='galeriavideos',
            name='slug',
            field=models.SlugField(default=1, editable=False, max_length=200),
            preserve_default=False,
        ),
    ]
