# Generated by Django 2.1.7 on 2019-08-05 20:10

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('galerias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galeriaimagenes',
            name='portada',
            field=sorl.thumbnail.fields.ImageField(upload_to='galerias/', verbose_name='Imagen'),
        ),
    ]
