# Generated by Django 2.1.7 on 2021-09-13 15:33

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('galerias', '0005_galeriaimagenes_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audios',
            name='portada',
            field=sorl.thumbnail.fields.ImageField(blank=True, help_text='830x620', null=True, upload_to='galerias/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='galeriaimagenes',
            name='portada',
            field=sorl.thumbnail.fields.ImageField(help_text='830x620', upload_to='galerias/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='galeriavideos',
            name='portada',
            field=sorl.thumbnail.fields.ImageField(blank=True, help_text='830x620', null=True, upload_to='galerias/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='imagenes',
            name='imagen',
            field=sorl.thumbnail.fields.ImageField(help_text='830x620', upload_to='galerias/'),
        ),
    ]
