# Generated by Django 2.1.7 on 2019-06-21 15:10

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields
import taggit_autosuggest.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actualidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=200, unique=True, verbose_name='Título')),
                ('category', models.CharField(choices=[('noticias', 'Noticias'), ('situacion-regional-genero', 'Situación regional de género'), ('campanas', 'Campañas'), ('concursos', 'Concursos')], max_length=50, verbose_name='Categoría')),
                ('photo', sorl.thumbnail.fields.ImageField(upload_to='actualidad/', verbose_name='Foto')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Contenido')),
                ('created_on', models.DateField(auto_now_add=True, verbose_name='Fecha de publicación')),
                ('slug', models.SlugField(editable=False, max_length=200)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('tags', taggit_autosuggest.managers.TaggableManager(blank=True, help_text='Separar elementos con "," ', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Actualidad',
                'verbose_name_plural': 'Actualidades',
                'ordering': ('-created_on', '-id'),
            },
        ),
        migrations.CreateModel(
            name='Temas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Tema',
                'verbose_name_plural': 'Temas',
            },
        ),
        migrations.AddField(
            model_name='actualidad',
            name='tematica',
            field=models.ManyToManyField(to='actualidad.Temas'),
        ),
    ]
