# Generated by Django 2.1.7 on 2019-05-06 17:27

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actualidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=200)),
                ('category', models.IntegerField(choices=[(1, 'Informemonos'), (2, 'Situación regional de genero'), (3, 'Reflexiones'), (4, 'Campañas'), (5, 'Concursos')])),
                ('photo', sorl.thumbnail.fields.ImageField(upload_to='actualidad/')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('created_on', models.DateField(auto_now_add=True, verbose_name='Fecha de publicación')),
                ('slug', models.SlugField(editable=False, max_length=200)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='Separar elementos con "," ', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Actualidad',
                'verbose_name_plural': 'Actualidades',
                'ordering': ('-created_on', '-id'),
            },
        ),
    ]
