# Generated by Django 2.1.7 on 2019-05-15 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actualidad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualidad',
            name='category',
            field=models.IntegerField(choices=[(1, 'Informémonos'), (2, 'Situación regional de género'), (3, 'Reflexiones'), (4, 'Campañas'), (5, 'Concursos')], verbose_name='Categoría'),
        ),
    ]
