# Generated by Django 2.1.7 on 2019-06-04 16:31

from django.db import migrations, models
import taggit_autosuggest.managers


class Migration(migrations.Migration):

    dependencies = [
        ('actualidad', '0002_auto_20190528_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualidad',
            name='category',
            field=models.CharField(choices=[('informemonos', 'Informémonos'), ('situacion-regional-genero', 'Situación regional de género'), ('reflexiones', 'Reflexiones'), ('campanas', 'Campañas'), ('concursos', 'Concursos')], max_length=50, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='actualidad',
            name='tags',
            field=taggit_autosuggest.managers.TaggableManager(blank=True, help_text='Separar elementos con "," ', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
