# Generated by Django 2.1.7 on 2019-08-05 20:10

from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('actualidad', '0002_actualidad_pais'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=90)),
                ('imagen', sorl.thumbnail.fields.ImageField(upload_to='galerias/actualidad/')),
                ('actualidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actualidad.Actualidad')),
            ],
        ),
    ]
