# Generated by Django 2.1.7 on 2019-06-11 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actualidad', '0004_auto_20190605_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualidad',
            name='created_on',
            field=models.DateField(verbose_name='Fecha de publicación'),
        ),
    ]
