# Generated by Django 2.1.7 on 2023-11-17 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actualidad', '0005_auto_20210913_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualidad',
            name='created_on',
            field=models.DateField(verbose_name='Fecha de publicación'),
        ),
    ]
