# Generated by Django 2.1.7 on 2019-05-31 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contraparte',
            options={'verbose_name_plural': 'Alianzas'},
        ),
    ]
