# Generated by Django 2.1.7 on 2019-09-23 14:52

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('organizaciones', '0002_auto_20190624_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contraparte',
            name='logo',
            field=sorl.thumbnail.fields.ImageField(blank=True, help_text='240x170', null=True, upload_to='contrapartes/logos/'),
        ),
    ]
