# Generated by Django 2.1.7 on 2026-03-02 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizaciones', '0004_auto_20191010_1255'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contraparte',
            options={'verbose_name_plural': 'Organizaciones afines'},
        ),
    ]
