# Generated by Django 2.1.7 on 2019-07-23 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siteconfiguration',
            options={'verbose_name': 'Configuracion imagenes del sitio'},
        ),
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name': 'Slider inicio'},
        ),
    ]
