# Generated by Django 2.1.7 on 2019-05-31 21:43

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='foto_quienes_somos',
            field=sorl.thumbnail.fields.ImageField(blank=True, help_text='1350x230', null=True, upload_to='configuracion/'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='foto_actualidad',
            field=sorl.thumbnail.fields.ImageField(blank=True, help_text='1350x230', null=True, upload_to='configuracion/'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='foto_eventos',
            field=sorl.thumbnail.fields.ImageField(blank=True, help_text='1350x230', null=True, upload_to='configuracion/'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='foto_foros',
            field=sorl.thumbnail.fields.ImageField(blank=True, help_text='1350x230', null=True, upload_to='configuracion/'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='foto_galerias_imagenes',
            field=sorl.thumbnail.fields.ImageField(blank=True, help_text='1350x230', null=True, upload_to='configuracion/'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='foto_galerias_videos',
            field=sorl.thumbnail.fields.ImageField(blank=True, help_text='1350x230', null=True, upload_to='configuracion/'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='foto_puntos_vista',
            field=sorl.thumbnail.fields.ImageField(blank=True, help_text='1350x230', null=True, upload_to='configuracion/'),
        ),
    ]
