# Generated by Django 2.1.7 on 2019-06-14 16:04

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0003_auto_20190605_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='foto_campanias',
            field=sorl.thumbnail.fields.ImageField(blank=True, help_text='1350x230', null=True, upload_to='configuracion/'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='foto_concursos',
            field=sorl.thumbnail.fields.ImageField(blank=True, help_text='1350x230', null=True, upload_to='configuracion/'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='foto_guias_metodologicas',
            field=sorl.thumbnail.fields.ImageField(blank=True, help_text='1350x230', null=True, upload_to='configuracion/'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='foto_publicaciones',
            field=sorl.thumbnail.fields.ImageField(blank=True, help_text='1350x230', null=True, upload_to='configuracion/'),
        ),
    ]
