# Generated by Django 2.1.7 on 2019-09-06 16:18

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0003_siteconfiguration_foto_galerias_audios'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='color_texto_1',
            field=colorfield.fields.ColorField(default=1, max_length=18),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slider',
            name='color_texto_2',
            field=colorfield.fields.ColorField(blank=True, max_length=18, null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='color_texto_3',
            field=colorfield.fields.ColorField(blank=True, max_length=18, null=True),
        ),
    ]
