# Generated by Django 2.1.7 on 2019-09-23 14:52

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0004_auto_20190906_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='foto_actualidad',
            field=sorl.thumbnail.fields.ImageField(blank=True, help_text='1400x300', null=True, upload_to='configuracion/'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='foto_alianzas',
            field=sorl.thumbnail.fields.ImageField(blank=True, help_text='1400x300', null=True, upload_to='configuracion/'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='foto_campanias',
            field=sorl.thumbnail.fields.ImageField(blank=True, help_text='1400x300', null=True, upload_to='configuracion/'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='foto_concursos',
            field=sorl.thumbnail.fields.ImageField(blank=True, help_text='1400x300', null=True, upload_to='configuracion/'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='foto_eventos',
            field=sorl.thumbnail.fields.ImageField(blank=True, help_text='1400x300', null=True, upload_to='configuracion/'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='foto_foros',
            field=sorl.thumbnail.fields.ImageField(blank=True, help_text='1400x300', null=True, upload_to='configuracion/'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='foto_galerias_audios',
            field=sorl.thumbnail.fields.ImageField(blank=True, help_text='1400x300', null=True, upload_to='configuracion/'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='foto_galerias_imagenes',
            field=sorl.thumbnail.fields.ImageField(blank=True, help_text='1400x300', null=True, upload_to='configuracion/'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='foto_galerias_videos',
            field=sorl.thumbnail.fields.ImageField(blank=True, help_text='1400x300', null=True, upload_to='configuracion/'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='foto_guias_metodologicas',
            field=sorl.thumbnail.fields.ImageField(blank=True, help_text='1400x300', null=True, upload_to='configuracion/'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='foto_publicaciones',
            field=sorl.thumbnail.fields.ImageField(blank=True, help_text='1400x300', null=True, upload_to='configuracion/'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='foto_puntos_vista',
            field=sorl.thumbnail.fields.ImageField(blank=True, help_text='1400x300', null=True, upload_to='configuracion/'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='foto_quienes_somos',
            field=sorl.thumbnail.fields.ImageField(blank=True, help_text='1400x300', null=True, upload_to='configuracion/'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='foto_1',
            field=sorl.thumbnail.fields.ImageField(help_text='1400x300', upload_to='slider/', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='foto_2',
            field=sorl.thumbnail.fields.ImageField(blank=True, help_text='1400x300', null=True, upload_to='slider/', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='foto_3',
            field=sorl.thumbnail.fields.ImageField(blank=True, help_text='1400x300', null=True, upload_to='slider/', verbose_name='Foto'),
        ),
    ]
