# Generated by Django 2.1.7 on 2019-11-13 14:53

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0005_auto_20190923_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='color_texto_1',
            field=colorfield.fields.ColorField(blank=True, max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='slider',
            name='credito_1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Credito'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='texto_1',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Texto'),
        ),
    ]
