# Generated by Django 2.1.7 on 2021-09-03 09:45

from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0006_auto_20191113_0853'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformacionDestacada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', sorl.thumbnail.fields.ImageField(upload_to='destacado/', verbose_name='Foto')),
                ('titulo', models.CharField(max_length=250)),
                ('link', models.URLField()),
                ('activo', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Información destacada',
            },
        ),
    ]
