# Generated by Django 2.1.7 on 2021-09-08 10:59

from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0007_informaciondestacada'),
    ]

    operations = [
        migrations.AddField(
            model_name='informaciondestacada',
            name='navegacion',
            field=models.IntegerField(choices=[(1, 'Interna'), (2, 'Externa')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='informaciondestacada',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='informaciondestacada',
            name='imagen',
            field=sorl.thumbnail.fields.ImageField(help_text='Formatos compatibles: gif, jpge, png. Tamaño: 300x224', upload_to='destacado/', verbose_name='Foto'),
        ),
    ]
