# Generated by Django 2.1.7 on 2023-11-15 22:00

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0008_auto_20210908_1059'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformacionAlianzas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('contenido', ckeditor_uploader.fields.RichTextUploadingField()),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Información Alianzas',
            },
        ),
        migrations.CreateModel(
            name='InformacionIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('contenido', ckeditor_uploader.fields.RichTextUploadingField()),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Información Index',
            },
        ),
        migrations.CreateModel(
            name='Redes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opcion', models.CharField(choices=[('chrome', 'Sitio web'), ('facebook', 'Facebook'), ('twitter', 'Twitter'), ('youtube', 'Youtube'), ('instagram', 'Instagram'), ('linkedin', 'Linkedin'), ('flickr', 'Flickr'), ('pinterest', 'Pinterest'), ('vimeo', 'Vimeo'), ('chrome', 'Otra')], max_length=25)),
                ('url', models.URLField()),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Red',
                'verbose_name_plural': 'Redes',
            },
        ),
    ]
