# Generated by Django 2.1.7 on 2023-11-15 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0009_informacionalianzas_informacionindex_redes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informacionalianzas',
            name='activo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='informacionindex',
            name='activo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='redes',
            name='opcion',
            field=models.CharField(choices=[('chrome', 'Sitio web'), ('facebook', 'Facebook'), ('twitter', 'Twitter'), ('youtube', 'Youtube'), ('instagram', 'Instagram'), ('linkedin', 'Linkedin'), ('flickr', 'Flickr'), ('pinterest', 'Pinterest'), ('vimeo', 'Vimeo'), ('otra', 'Otra')], max_length=25),
        ),
    ]
