# Generated by Django 2.1.7 on 2019-06-19 17:57

import ckeditor_uploader.fields
from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Puntos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=200, unique=True, verbose_name='Título')),
                ('foto', sorl.thumbnail.fields.ImageField(upload_to='puntos-vista/', verbose_name='Foto')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de publicación')),
                ('contenido', ckeditor_uploader.fields.RichTextUploadingField()),
                ('slug', models.SlugField(editable=False, max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Puntos',
            },
        ),
    ]
