# Generated by Django 2.1.7 on 2021-09-13 15:33

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('puntosvista', '0004_auto_20190923_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puntos',
            name='foto',
            field=sorl.thumbnail.fields.ImageField(help_text='830x620', upload_to='puntos-vista/', verbose_name='Foto'),
        ),
    ]
