# Generated by Django 2.1.7 on 2021-08-12 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compromisos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compromiso',
            name='total',
            field=models.IntegerField(default=1, editable=False),
            preserve_default=False,
        ),
    ]
