# Generated by Django 2.1.7 on 2021-09-03 09:35

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('compromisos', '0003_auto_20210826_0944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fotoscompromisos',
            name='compromiso',
        ),
        migrations.AddField(
            model_name='compromiso',
            name='foto',
            field=sorl.thumbnail.fields.ImageField(default=1, upload_to='compromisos/'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='FotosCompromisos',
        ),
    ]
