# Generated by Django 2.1.7 on 2019-09-23 14:52

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0004_auto_20190820_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='imagen',
            field=sorl.thumbnail.fields.ImageField(blank=True, help_text=' 612px de ancho', null=True, upload_to='publicaciones/img/'),
        ),
    ]
