# Generated by Django 2.1.7 on 2021-08-11 14:02

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('publicaciones', '0005_auto_20190923_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='palabras_claves',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Palabras claves'),
        ),
    ]
