# Generated by Django 2.1.7 on 2026-02-27 19:48

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('actualidad', '0006_auto_20231117_1256'),
        ('publicaciones', '0007_auto_20210826_0944'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPublicacion',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
                ('imagen', models.TextField(blank=True, help_text=' 612px de ancho', max_length=100, null=True)),
                ('resumen', ckeditor_uploader.fields.RichTextUploadingField()),
                ('tipo', models.IntegerField(choices=[(1, 'Publicaciones'), (2, 'Guías metodológicas')], default=1, editable=False)),
                ('slug', models.SlugField(editable=False, max_length=250)),
                ('aprobado', models.BooleanField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tematica', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='actualidad.Temas')),
                ('usuario', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'historical publicacion',
                'verbose_name_plural': 'historical Publicaciones',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
