# Generated by Django 2.1.7 on 2026-02-28 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0008_historicalpublicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpublicacion',
            name='created_on',
            field=models.DateField(blank=True, editable=False, null=True, verbose_name='Fecha de publicación'),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='created_on',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Fecha de publicación'),
        ),
    ]
