# Generated by Django 2.1.7 on 2026-03-02 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0009_auto_20260228_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreguntasPublicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utilizara_material', models.IntegerField(choices=[(1, '')], verbose_name='¿Para qué utilizará este material?')),
                ('perfil', models.IntegerField(choices=[(1, 'Educador/a'), (2, 'Multiplicador/a'), (3, 'Estudiante'), (4, 'Organización')], verbose_name='¿Para qué utilizará este material?')),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publicaciones.Publicacion')),
            ],
        ),
    ]
