# Generated by Django 2.1.7 on 2026-03-04 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0010_preguntaspublicacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='RespMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name_plural': '¿Para qué utilizará este material?',
            },
        ),
        migrations.AlterField(
            model_name='preguntaspublicacion',
            name='perfil',
            field=models.IntegerField(choices=[(1, 'Educador/a o facilitador/a'), (2, 'Multiplicador/a comunitario/a'), (3, 'Estudiante'), (4, 'Integrante de organización social'), (5, 'Investigador/a o académico/a'), (6, 'Funcionaria/o público'), (7, 'Integrante de ONG o cooperación internacional'), (8, 'Consultor/a o profesional independiente'), (9, 'Persona interesada en temas de género'), (10, 'Otro')], verbose_name='¿Cuál es su perfil?'),
        ),
        migrations.RemoveField(
            model_name='preguntaspublicacion',
            name='utilizara_material',
        ),
        migrations.AddField(
            model_name='preguntaspublicacion',
            name='utilizara_material',
            field=models.ManyToManyField(to='publicaciones.RespMaterial', verbose_name='¿Para qué utilizará este material? (Puede seleccionar una o más opciones)'),
        ),
    ]
