# Generated by Django 2.1.7 on 2026-03-14 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0011_auto_20260304_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preguntaspublicacion',
            name='perfil',
            field=models.IntegerField(choices=[(1, 'Educador/a o facilitador/a'), (2, 'Multiplicador/a comunitario/a'), (3, 'Estudiante'), (4, 'Integrante de organización social'), (5, 'Investigador/a o académico/a'), (6, 'Funcionaria/o público'), (7, 'Integrante de ONG o cooperación internacional'), (8, 'Consultor/a o profesional independiente'), (9, 'Persona interesada en temas de género')], verbose_name='¿Cuál es su perfil?'),
        ),
    ]
