# Generated by Django 2.1.7 on 2023-11-15 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0002_auto_20231115_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudesorg',
            name='organizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='organizaciones.Contraparte'),
        ),
    ]
