# Generated by Django 2.1.7 on 2019-08-06 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foros',
            name='aprobado',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
