# Generated by Django 2.1.7 on 2019-06-11 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foro', '0002_auto_20190528_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foros',
            name='creacion',
            field=models.DateField(verbose_name='Fecha de creación'),
        ),
    ]
