# Generated by Django 2.1.7 on 2019-06-12 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foro', '0002_auto_20190528_1018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foros',
            name='apertura',
        ),
        migrations.RemoveField(
            model_name='foros',
            name='cierre',
        ),
    ]
