# Generated by Django 2.1.7 on 2021-08-12 13:25

from django.db import migrations, models
import embed_video.fields
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('foro', '0002_foros_aprobado'),
    ]

    operations = [
        migrations.AddField(
            model_name='foros',
            name='tipo_portada',
            field=models.IntegerField(choices=[(1, 'Foto'), (2, 'Video')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='foros',
            name='url_video',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='foros',
            name='foto',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='foros/', verbose_name='Foto'),
        ),
    ]
