# Generated by Django 2.1.7 on 2021-09-13 15:33

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('foro', '0003_auto_20210812_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foros',
            name='foto',
            field=sorl.thumbnail.fields.ImageField(default=1, help_text='830x620', upload_to='foros/', verbose_name='Foto'),
            preserve_default=False,
        ),
    ]
