# Generated by Django 2.1.7 on 2019-06-12 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foro', '0003_auto_20190612_1026'),
        ('foro', '0003_auto_20190611_1018'),
    ]

    operations = [
    ]
