# Generated by Django 2.1.7 on 2019-06-14 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foro', '0004_merge_20190612_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foros',
            name='creacion',
            field=models.DateField(auto_now_add=True),
        ),
    ]
