# Generated by Django 2.1.7 on 2019-05-17 15:19

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import location_field.models.plain
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=200, verbose_name='Título')),
                ('foto', sorl.thumbnail.fields.ImageField(upload_to='eventos/', verbose_name='Foto')),
                ('descripcion', ckeditor_uploader.fields.RichTextUploadingField()),
                ('inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('final', models.DateField(blank=True, null=True, verbose_name='Fecha de Finalización')),
                ('hora_inicio', models.TimeField(verbose_name='Hora inicio')),
                ('hora_fin', models.TimeField(verbose_name='Hora fin')),
                ('city', models.CharField(max_length=100, verbose_name='Dirección')),
                ('position', location_field.models.plain.PlainLocationField(max_length=63, verbose_name='Posición')),
                ('slug', models.SlugField(editable=False, max_length=200)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Eventos',
            },
        ),
    ]
