# Generated by Django 2.1.7 on 2019-06-19 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit_autosuggest.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('evento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evento',
            name='tags',
            field=taggit_autosuggest.managers.TaggableManager(blank=True, help_text='Separar elementos con "," ', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
