# Generated by Django 2.1.7 on 2019-05-28 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='tittle',
            field=models.CharField(max_length=200, unique=True, verbose_name='Título'),
        ),
    ]
