# Generated by Django 2.1.7 on 2019-06-04 20:10

from django.db import migrations
import taggit_autosuggest.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('evento', '0002_auto_20190528_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='tags',
            field=taggit_autosuggest.managers.TaggableManager(blank=True, help_text='Separar elementos con "," ', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
