# Generated by Django 2.1.7 on 2019-11-04 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0005_auto_20190923_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora inicio'),
        ),
    ]
