# Generated by Django 2.1.7 on 2021-09-13 15:33

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0006_auto_20191104_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='foto',
            field=sorl.thumbnail.fields.ImageField(help_text='830x620', upload_to='eventos/', verbose_name='Foto'),
        ),
    ]
